//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por PIA ESTRUCTURAS.rc
//
#define BTN_EDITM                       3
#define IDEDITCL                        3
#define IDCANCEL2                       4
#define BTN_DELETEM                     4
#define IDDELCL                         4
#define IDEDIT                          6
#define IDDELETE                        7
#define IDD_MAIN                        101
#define IDR_MENU1                       103
#define IDD_SERVICES                    104
#define IDD_MECHS                       106
#define IDD_CITAS                       108
#define IDD_CLIENTS                     110
#define IDD_LOGIN                       112
#define TB_USER                         1001
#define TB_PASS                         1002
#define BN_SALIR                        1003
#define ST_USERMA                       1004
#define ST_TIMERMA                      1005
#define PC_USERMA                       1006
#define Lbl_Timer                       1007
#define RB_REGIST                       1008
#define RB_RED                          1009
#define RB_REDIT                        1009
#define TB_NAME                         1010
#define TB_DESC                         1011
#define BN_OKESP                        1012
#define BN_CANCELESP                    1013
#define LBL_NOTE                        1014
#define LBL_NAME                        1015
#define LBL_ESP                         1016
#define LBL_CHOOSE                      1017
#define LBL_USERNAME                    1018
#define BN_EDIT                         1018
#define BN_SAIRMAIN                     1019
#define RB_REP                          1019
#define RB_REPSERV                      1019
#define TB_COST                         1020
#define DTP_CITS                        1021
#define LBL_NAME2                       1021
#define LB_CITAS                        1022
#define BTN_DELETES                     1022
#define IDC_RADIO1                      1023
#define RB_RCL                          1023
#define IDC_RADIO2                      1024
#define RB_CL                           1024
#define RB_RCIT                         1024
#define RB_CITPEN                       1024
#define IDC_EDIT1                       1025
#define IDC_RADIO3                      1025
#define IDC_EDIT2                       1026
#define IDC_EDIT3                       1027
#define IDC_COMBO1                      1028
#define IDC_EDIT12                      1028
#define CB_SERVCT                       1028
#define IDC_COMBO2                      1029
#define IDC_BUTTON1                     1030
#define IDC_EDIT5                       1030
#define BTN_LOADM                       1030
#define IDC_COMBO4                      1030
#define BTN_BINSEARCH                   1030
#define IDC_EDIT4                       1031
#define IDC_DATETIMEPICKER1             1031
#define TB_TELM                         1031
#define CB_HOUR                         1031
#define PB_AppL                         1032
#define IDC_EDIT6                       1032
#define IDC_COMBO3                      1033
#define IDC_LIST1                       1033
#define LB_SERV                         1033
#define CB_SERVM                        1033
#define IDC_EDIT7                       1033
#define TB_NAMEM                        1034
#define IDC_EDIT8                       1034
#define CB_SCHEDW                       1035
#define IDC_EDIT9                       1035
#define CB_SCHEDH                       1036
#define RB_BCLIENT                      1036
#define PC_MECH                         1037
#define IDC_EDIT11                      1037
#define RB_REPM                         1038
#define IDC_EDIT10                      1038
#define TB_APEL                         1038
#define RB_REGM                         1039
#define LBL_NUMEMP                      1040
#define IDC_LIST2                       1041
#define LB_MECS                         1041
#define LB_CL                           1041
#define LBL_PIC                         1042
#define CH_ATT                          1043
#define CH_CANC                         1044
#define CB_CLIENT                       1045
#define CB_MECH                         1046
#define PC_CITAS                        1047
#define TB_TEL                          1048
#define LBL_FOLIO                       1049
#define IDC_STATICLBL                   1050
#define IDC_STATICS                     1051
#define IDC_STATICM                     1052
#define IDC_STATICP                     1053
#define IDC_STATICC                     1054
#define IDC_STATICT                     1055
#define IDC_STATICF                     1056
#define IDC_STATICH                     1057
#define IDC_STATICPM                    1058
#define RB_BFO                          1059
#define RB_MECH                         1060
#define RB_MON                          1061
#define RB_WEEK                         1062
#define RB_BSER                         1063
#define DTP_BUS                         1064
#define TB_FOLIOB                       1065
#define CB_SERVB                        1066
#define CB_MECHB                        1067
#define LBL_INST                        1068
#define TB_BIGDIR                       1069
#define LBL_CANCELDESC                  1069
#define IDC_STATICCA                    1070
#define IDC_STATICNUM                   1071
#define IDC_STATICCOL                   1072
#define IDC_STATICMUN                   1073
#define IDC_STATICSTATE                 1074
#define LBL_USERCL                      1075
#define TB_CANCELDESC                   1076
#define LBL_USERCT                      1077
#define LBL_USERM                       1078
#define LBL_USERS                       1079
#define LBL_FECHA                       1080
#define ID_CANCELC                      1081
#define IDC_RADIO4                      1082
#define IDC_RADIO5                      1083
#define IDC_RADIO6                      1084
#define IDC_RADIO7                      1085
#define IDC_STATICB                     1086
#define IDC_STATICBIN                   1086
#define ID_CITAS_REGISTRODECITAS        40003
#define ID_CONSULTADECITAS_PORMES       40006
#define ID_CONSULTADECITAS_PORSEMANA    40007
#define ID_CONSULTADECITAS_PORESPECIALIDAD 40008
#define ID_MEDICOS_REGISTRODEMEDICOS    40009
#define ID_MEDICOS_REPORTEDEMEDICOS     40010
#define ID_ESPECIALIDADES_REGISTRODEESPECIALIDADES 40011
#define ID_ESPECIALIDADES_REPORTEDEESPECIALIDADES 40012
#define ID_SALIR                        40013
#define ID_ESPECIALIDADES               40014
#define ID_MEDICOS                      40015
#define ID_CITAS                        40016
#define ID_PACIENTES                    40017

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        114
#define _APS_NEXT_COMMAND_VALUE         40018
#define _APS_NEXT_CONTROL_VALUE         1087
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
